### ISSUE TITLE
RE: Hello Sir/Seth

### ISSUE THREAD

**Issue by silver2row** [autonome/context#4]
Hello,

I just purchased a FireFox OS system phone on ebay.com. I found one of your talks online and thought, "This sounds very interesting." So, what the hell? I tried it out. 

Currently, I am using a BeagleBone Black and/or variants of the BBB. I am running Linux Stretch, kernel 4.9.x from https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#Checking_The_Debian_Image_Version.

I was wondering if you had any updates on specific boards that may work with this idea.

Seth

P.S. If so and if you are still using this idea and updating the info, will you please supply some resources. I would like to get started right away and use the Linux Distro I currently have on my BBB to start software development. I am a newbie of sorts and really think this is something valuable.

**Comment by autonome** [comment]
Hey Seth!

The concept behind this code is pretty flexible - it'll work anywhere
there's a working web runtime (something that can open and run web pages
with javascript).

The variable part is which physical "sensors" are available on the device,
and in the browser.

For example, a typical smartphone has an accelerometer, gyroscope,
microphone, camera, and GPS all exposed to the browser as JavaScript APIs.
This means you can run Context, and build adapters that make assertions
about readings from those, without any special modifications.

For Firefox OS, you have additional APIs for proximity, ambient light,
Bluetooth, and more.

For something like a BBB, you likely have *none* of the sensors listed
above available in the web runtime. This doesn't mean you can't take the
same approach, you just need to add a connector to send data from sensors
you attach to the board out to the web runtime. Typically this is done by a
web socket.

For example, imagine a node.js script that is a web server that serves up
Context, and also uses Johnny-five to get data from the sensors you
attached to the BBB, and uses ws to send that data out to Context via a web
socket. You'd need to write a new module for Context that opens up a web
socket and returns the data, but if you look at the module format, it's
quite simple.

Good luck. Happy to answer more questions if you have them.

**Comment by silver2row** [comment]
Hello Sir,

Thank you for replying. Is there a way to hack the Firefox phone to allow me to program it outside of using the sensors built into the phone? 

I was wondering because I feel like I could write some JavaScript software to promote the change in sensors around another device, SoCs or SiPs like a BBB/BBG. I am just unsure about the Firefox OS for now. I saw on the phone there was a developer's section. 

With these phones, is it possible to add or subtract available software without adding applications that are user-friendly? I do not want to make something spectacular. I just want to use your idea to run some basic notifications on sensors around the house. 

Like, for instance, my idea was that I could use the BBB to write the software and then upload it to the Firefox OS phone. I see I misunderstood, I think.

Seth

P.S. I guess what is being produced is okay in the end. I would be producing an attachment of the phone capabilities and displaying them "graphically" in the wed or at a specific web address, right? It is a cool idea. I like the fact that, and this is what you stated in your talk, the phone can then produce after the power goes out. This is an extra layer of security if something was to change.

**Comment by autonome** [comment]
> I am just unsure about the Firefox OS for now.

It is a canceled project, sadly.

> producing an attachment of the phone capabilities and displaying
> them "graphically" in the wed or at a specific web address, right?

Yeah! If I understand correctly: Yes, you can use the phone as the sensor,
and then send that data anywhere you want using typical web communication
techniques, like HTTP POSTing that data to another server, or whatever you
like.

**Comment by silver2row** [comment]
Yep...I see the OS project has been canceled but the Mozilla people still have it on their site. I will keep up hope.

Seth

P.S. Thank you for replying.
